apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
  - mappingMethod: claim
    name: azure-openid
    openID:
      ca:
        name: openshift-ca
      claims:
        email:
        - email
        name:
        - name
        preferredUsername:
        - preferred_username
      clientID: b3f6f2bc-4ac5-492b-a2ad-deda2b1a1edf
      clientSecret:
        name: azure-client-secret
      extraScopes: []
      issuer: https://login.microsoftonline.com/2598639a-d083-492d-bdbe-f1dd8066b03a
    type: OpenID
