kind: ClusterSecretStore
apiVersion: external-secrets.io/v1beta1
metadata:
  name: awssm
  namespace: openshift-operators
spec:
  controller: awssm
  provider:
    aws:
      auth:
        secretRef:
          accessKeyIDSecretRef:
            key: access-key
            name: awssm-reader
            namespace: openshift-operators
          secretAccessKeySecretRef:
            key: secret-access-key
            name: awssm-reader
            namespace: openshift-operators
      region: eu-central-1
      service: SecretsManager