apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: repo-secret
  namespace: argocd
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: awssm #The secret store name we have just created.
    kind: ClusterSecretStore
  data:
  - secretKey: sshPrivateKey # which key it's going to be stored
    remoteRef:
      key: argocd # Our secret-name goes here
