apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: argocd-operator
  namespace: openshift-operators
spec:
  channel: alpha
  name: argocd-operator
  source: community-operators 
  sourceNamespace: openshift-marketplace 
  config:
    env:
    - name: ARGOCD_CLUSTER_CONFIG_NAMESPACES
      value: argocd