apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: maistraoperator
  namespace: openshift-operators
spec:
  channel: stable
  name: maistraoperator
  source: community-operators 
  sourceNamespace: openshift-marketplace 
